/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplication;

import controlers.FacturasJpaController;
import entities.Facturas;
import java.awt.Color;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joseangel
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacion8_2
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaPrincipal = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        BotonActualizarBorrar = new javax.swing.JButton();
        BotonAñadir = new javax.swing.JButton();
        BotonConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VentanaPrincipal.setBackground(new java.awt.Color(27, 156, 133));
        VentanaPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(255, 225, 148));
        Titulo.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(232, 246, 239));
        Titulo.setText("Operaciones tabla Factura");
        VentanaPrincipal.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 610, 90));

        BotonActualizarBorrar.setBackground(new java.awt.Color(76, 76, 109));
        BotonActualizarBorrar.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        BotonActualizarBorrar.setForeground(new java.awt.Color(255, 225, 148));
        BotonActualizarBorrar.setText("Actualizar / Borrar Factura");
        BotonActualizarBorrar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(232, 246, 239)));
        BotonActualizarBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonActualizarBorrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonActualizarBorrarMouseExited(evt);
            }
        });
        BotonActualizarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarBorrarActionPerformed(evt);
            }
        });
        VentanaPrincipal.add(BotonActualizarBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 820, 60));

        BotonAñadir.setBackground(new java.awt.Color(76, 76, 109));
        BotonAñadir.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        BotonAñadir.setForeground(new java.awt.Color(255, 225, 148));
        BotonAñadir.setText("Añadir Facturas");
        BotonAñadir.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(232, 246, 239)));
        BotonAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonAñadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonAñadirMouseExited(evt);
            }
        });
        BotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirActionPerformed(evt);
            }
        });
        VentanaPrincipal.add(BotonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 400, 60));

        BotonConsultar.setBackground(new java.awt.Color(76, 76, 109));
        BotonConsultar.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        BotonConsultar.setForeground(new java.awt.Color(255, 225, 148));
        BotonConsultar.setText("Consultar Facturas");
        BotonConsultar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(232, 246, 239)));
        BotonConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonConsultarMouseExited(evt);
            }
        });
        BotonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarActionPerformed(evt);
            }
        });
        VentanaPrincipal.add(BotonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 400, 60));

        getContentPane().add(VentanaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 878, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonActualizarBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonActualizarBorrarMouseEntered
        // TODO add your handling code here:
        BotonActualizarBorrar.setBackground(new java.awt.Color(232, 246, 239));
    }//GEN-LAST:event_BotonActualizarBorrarMouseEntered

    private void BotonActualizarBorrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonActualizarBorrarMouseExited
        // TODO add your handling code here:
        BotonActualizarBorrar.setBackground(new java.awt.Color(76, 76, 109));
    }//GEN-LAST:event_BotonActualizarBorrarMouseExited

    private void BotonAñadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAñadirMouseEntered
        // TODO add your handling code here:
        BotonAñadir.setBackground(new java.awt.Color(232, 246, 239));
    }//GEN-LAST:event_BotonAñadirMouseEntered

    private void BotonAñadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAñadirMouseExited
        // TODO add your handling code here:
        BotonAñadir.setBackground(new java.awt.Color(76, 76, 109));
    }//GEN-LAST:event_BotonAñadirMouseExited

    private void BotonActualizarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarBorrarActionPerformed
        // TODO add your handling code here:

        // crear la ventana nueva
        VentanaActualizarBorrar ventana = new VentanaActualizarBorrar();
        // hacerla visible
        ventana.setVisible(true);

        // hacer que se cierre esta ventana y abrir la nueva
        this.dispose();

    }//GEN-LAST:event_BotonActualizarBorrarActionPerformed

    private void BotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirActionPerformed
        // TODO add your handling code here:

        // crear la ventana nueva
        VentanaAñadir ventana = new VentanaAñadir();
        // hacerla visible
        ventana.setVisible(true);

        // hacer que se cierre esta ventana y abrir la nueva
        this.dispose();


    }//GEN-LAST:event_BotonAñadirActionPerformed

    private void BotonConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonConsultarMouseEntered
        // TODO add your handling code here:
        BotonConsultar.setBackground(new java.awt.Color(232, 246, 239));
    }//GEN-LAST:event_BotonConsultarMouseEntered

    private void BotonConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonConsultarMouseExited
        // TODO add your handling code here:
        BotonConsultar.setBackground(new java.awt.Color(76, 76, 109));
    }//GEN-LAST:event_BotonConsultarMouseExited

    private void BotonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarActionPerformed
        // TODO add your handling code here:

        // crear la ventana nueva
        VentanaConsulta ventana = new VentanaConsulta();
        // hacerla visible
        ventana.setVisible(true);

        // hacer que se cierre esta ventana y abrir la nueva
        this.dispose();

        // los datos de la consulta, se obitnenen y muestran con el evento 
        // windows opener al abrir la ventana consulta
        
        

    }//GEN-LAST:event_BotonConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizarBorrar;
    private javax.swing.JButton BotonAñadir;
    private javax.swing.JButton BotonConsultar;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel VentanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
