/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import com.fasterxml.jackson.core.JsonProcessingException;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.text.DecimalFormat;
import modelo.Huella;
import serviciojson.JsonService;

/**
 *
 * @author joseangel
 */
public class InterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HuellaCarbono = new javax.swing.JPanel();
        botonMedir = new javax.swing.JButton();
        introducirURL = new javax.swing.JTextField();
        fabrica = new javax.swing.JLabel();
        textoIntroducirURL = new javax.swing.JLabel();
        textoCabecera = new javax.swing.JLabel();
        nubes = new javax.swing.JLabel();
        PanelDatos = new javax.swing.JPanel();
        textoZonaVerde1 = new javax.swing.JLabel();
        salidaVerde = new javax.swing.JLabel();
        bola4 = new javax.swing.JLabel();
        textoBytes = new javax.swing.JLabel();
        salidaBytes = new javax.swing.JLabel();
        bola5 = new javax.swing.JLabel();
        textoMasLimpia = new javax.swing.JLabel();
        salidaCleanerThan = new javax.swing.JLabel();
        bola6 = new javax.swing.JLabel();
        textoEnergiaConsumida = new javax.swing.JLabel();
        salidaEnergiaConsumida = new javax.swing.JLabel();
        bola1 = new javax.swing.JLabel();
        salidaRedCo2 = new javax.swing.JLabel();
        textoRedCo2 = new javax.swing.JLabel();
        bola7 = new javax.swing.JLabel();
        NubeCo2 = new javax.swing.JLabel();
        textoMasLimpia2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HuellaCarbono.setBackground(new java.awt.Color(51, 204, 255));
        HuellaCarbono.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        HuellaCarbono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMedir.setBackground(new java.awt.Color(51, 204, 255));
        botonMedir.setForeground(new java.awt.Color(255, 255, 255));
        botonMedir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/huella.png"))); // NOI18N
        botonMedir.setBorder(null);
        botonMedir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMedirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMedirMouseExited(evt);
            }
        });
        botonMedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMedirActionPerformed(evt);
            }
        });
        HuellaCarbono.add(botonMedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 220, 120));

        introducirURL.setBackground(new java.awt.Color(255, 255, 255));
        introducirURL.setForeground(new java.awt.Color(0, 0, 0));
        introducirURL.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        HuellaCarbono.add(introducirURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 410, 28));

        fabrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Fábrica.png"))); // NOI18N
        HuellaCarbono.add(fabrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 250, 280));

        textoIntroducirURL.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        textoIntroducirURL.setForeground(new java.awt.Color(255, 255, 255));
        textoIntroducirURL.setText("<html> <p>Introduce una dirección web para comprobarlo:</p> </html> ");
        HuellaCarbono.add(textoIntroducirURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 430, 40));

        textoCabecera.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        textoCabecera.setForeground(new java.awt.Color(255, 255, 255));
        textoCabecera.setText("¿Cúanto contamina la visita a una web?");
        textoCabecera.setToolTipText("");
        HuellaCarbono.add(textoCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 830, 150));

        nubes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/nubes.png"))); // NOI18N
        HuellaCarbono.add(nubes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 940, 430));

        PanelDatos.setBackground(new java.awt.Color(0, 204, 204));
        PanelDatos.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        PanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoZonaVerde1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        textoZonaVerde1.setForeground(new java.awt.Color(255, 255, 255));
        textoZonaVerde1.setText("<html> <p>¿La página web <br> está alojada en un <br> dominio verde ?</p> </html> ");
        PanelDatos.add(textoZonaVerde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 200, 100));

        salidaVerde.setFont(new java.awt.Font("Comic Sans MS", 1, 100)); // NOI18N
        salidaVerde.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelDatos.add(salidaVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 110, 120));

        bola4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/bolaMundo.png"))); // NOI18N
        PanelDatos.add(bola4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 190, 190));

        textoBytes.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        textoBytes.setForeground(new java.awt.Color(255, 255, 255));
        textoBytes.setText("<html>Mientras la web cargaba <br> se han transferido: </html>");
        textoBytes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelDatos.add(textoBytes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 220, 80));

        salidaBytes.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        salidaBytes.setForeground(new java.awt.Color(255, 255, 255));
        PanelDatos.add(salidaBytes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 110, 110));

        bola5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/bolaMundo.png"))); // NOI18N
        PanelDatos.add(bola5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 190, 190));

        textoMasLimpia.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        textoMasLimpia.setForeground(new java.awt.Color(255, 255, 255));
        textoMasLimpia.setText("<html> La web es mas <br> limpia que el:</html>");
        PanelDatos.add(textoMasLimpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 160, 90));

        salidaCleanerThan.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        PanelDatos.add(salidaCleanerThan, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 110, 110));

        bola6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/bolaMundo.png"))); // NOI18N
        PanelDatos.add(bola6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 190, 190));

        textoEnergiaConsumida.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        textoEnergiaConsumida.setForeground(new java.awt.Color(255, 255, 255));
        textoEnergiaConsumida.setText("Energía consumida:");
        PanelDatos.add(textoEnergiaConsumida, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, -1, 30));

        salidaEnergiaConsumida.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        salidaEnergiaConsumida.setForeground(new java.awt.Color(255, 255, 255));
        PanelDatos.add(salidaEnergiaConsumida, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 110, 110));

        bola1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/bolaMundo.png"))); // NOI18N
        PanelDatos.add(bola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 190, 190));

        salidaRedCo2.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        salidaRedCo2.setForeground(new java.awt.Color(255, 255, 255));
        PanelDatos.add(salidaRedCo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 110, 110));

        textoRedCo2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        textoRedCo2.setForeground(new java.awt.Color(255, 255, 255));
        textoRedCo2.setText("<html> <p>Cantidad Co2 emitida <br> por energía de la red pública:</p> </html> ");
        PanelDatos.add(textoRedCo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, 60));

        bola7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/bolaMundo.png"))); // NOI18N
        PanelDatos.add(bola7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, 190));

        NubeCo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/nubeCo2.png"))); // NOI18N
        PanelDatos.add(NubeCo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 360, 320));

        textoMasLimpia2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        textoMasLimpia2.setForeground(new java.awt.Color(255, 255, 255));
        textoMasLimpia2.setText("<html>de webs que se han probado</html>");
        PanelDatos.add(textoMasLimpia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HuellaCarbono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HuellaCarbono, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMedirActionPerformed
        // TODO add your handling code here:
        // si se pulsa el boton medir
        if (evt.getSource().equals(botonMedir)) {

            // se obtiene la url donde se hace la consulta
            final String urlBase = "https://api.websitecarbon.com/site?url=";
            // se obtiene la url que ha introducido el usuario
            String urlUsuario = introducirURL.getText();
            // obtener la url completa
            String urlCompleta = urlBase.concat(urlUsuario);
            // realizamos la conexion a la url para obtener los datos y guardarlo
            String fichero = "";
            try {
                fichero = conexion_http.ConexionHTTP.peticionHttpGet(urlCompleta);
            } catch (IOException ex) {
                System.out.println("La petición de datos no se ha podido realizar");
            }

            // convertir nuestro fichero a pojo
            Huella huella = new Huella();
            try {
                huella = (Huella) JsonService.stringToPojo(fichero, modelo.Huella.class);
            } catch (JsonProcessingException ex) {
                System.out.println("Los datos no se han podido transformar");
            }

            // una vez tenemos nuestro objeto huella con los datos
            // mostrarlos al usuario
            // zona verde
            if (huella.getGreen().equals("true")) {
                salidaVerde.setFont(new Font("Comic sans SM", Font.BOLD, 100));

                salidaVerde.setText("Sí");
                salidaVerde.setForeground(Color.GREEN);

            } else if (huella.getGreen().equals("false")) {
                salidaVerde.setFont(new Font("Comic sans SM", Font.BOLD, 100));

                salidaVerde.setText("No");
                salidaVerde.setForeground(Color.RED);
            } else {
                salidaVerde.setFont(new Font("Comic sans SM", Font.BOLD, 14));
                salidaVerde.setText("Desconocido");
                salidaVerde.setForeground(Color.BLACK);

            }

            // decimal format para obtener solo 2 decimales
            DecimalFormat df = new DecimalFormat("#.##");

            //bytes
            double bytes = huella.getBytes();
            salidaBytes.setText(df.format(bytes).concat("b"));

            // cleanerThan
            double cleanerThan = huella.getCleanerThan();
            cleanerThan = cleanerThan * 100;
            if (cleanerThan >= 51) {
                salidaCleanerThan.setForeground(Color.GREEN);
            } else {
                salidaCleanerThan.setForeground(Color.RED);
            }
            salidaCleanerThan.setText(df.format(cleanerThan).concat("%"));

            // energy
            double energy = huella.getStatistics().getEnergy();
            salidaEnergiaConsumida.setText(df.format(energy).concat("KW/g"));

            // co2 grid
            double gridLitres = huella.getStatistics().getCo2().getGrid().getLitres();
            salidaRedCo2.setText(df.format(gridLitres).concat("L"));

        }
    }//GEN-LAST:event_botonMedirActionPerformed

    private void botonMedirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMedirMouseExited
        // TODO add your handling code here:
        botonMedir.setBackground(new java.awt.Color(51, 204, 255));
    }//GEN-LAST:event_botonMedirMouseExited

    private void botonMedirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMedirMouseEntered
        // TODO add your handling code here:
        botonMedir.setBackground(Color.WHITE);
    }//GEN-LAST:event_botonMedirMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HuellaCarbono;
    private javax.swing.JLabel NubeCo2;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JLabel bola1;
    private javax.swing.JLabel bola4;
    private javax.swing.JLabel bola5;
    private javax.swing.JLabel bola6;
    private javax.swing.JLabel bola7;
    private javax.swing.JButton botonMedir;
    private javax.swing.JLabel fabrica;
    private javax.swing.JTextField introducirURL;
    private javax.swing.JLabel nubes;
    private javax.swing.JLabel salidaBytes;
    private javax.swing.JLabel salidaCleanerThan;
    private javax.swing.JLabel salidaEnergiaConsumida;
    private javax.swing.JLabel salidaRedCo2;
    private javax.swing.JLabel salidaVerde;
    private javax.swing.JLabel textoBytes;
    private javax.swing.JLabel textoCabecera;
    private javax.swing.JLabel textoEnergiaConsumida;
    private javax.swing.JLabel textoIntroducirURL;
    private javax.swing.JLabel textoMasLimpia;
    private javax.swing.JLabel textoMasLimpia2;
    private javax.swing.JLabel textoRedCo2;
    private javax.swing.JLabel textoZonaVerde1;
    // End of variables declaration//GEN-END:variables
}
