/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacion;

/**
 *
 * @author Jose Angel
 */
public class Main_Aplicacion_83 extends javax.swing.JFrame {

    /**
     * Creates new form Main_Aplicacion_83
     */
    public Main_Aplicacion_83() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAñadirProveedores = new javax.swing.JButton();
        BotonGenerarFactura = new javax.swing.JButton();
        BotonAñadirProductos = new javax.swing.JButton();
        BotonAñadirClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAñadirProveedores.setBackground(new java.awt.Color(70, 73, 75));
        BotonAñadirProveedores.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonAñadirProveedores.setText("Añadir / Actualizar Proveedores");
        BotonAñadirProveedores.setBorder(null);
        BotonAñadirProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirProveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAñadirProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 380, 50));

        BotonGenerarFactura.setBackground(new java.awt.Color(70, 73, 75));
        BotonGenerarFactura.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonGenerarFactura.setText("Generar Factura");
        BotonGenerarFactura.setBorder(null);
        BotonGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGenerarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(BotonGenerarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 260, 50));

        BotonAñadirProductos.setBackground(new java.awt.Color(70, 73, 75));
        BotonAñadirProductos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonAñadirProductos.setText("Añadir / Actualizar Productos");
        BotonAñadirProductos.setBorder(null);
        BotonAñadirProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirProductosActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAñadirProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 380, 50));

        BotonAñadirClientes.setBackground(new java.awt.Color(70, 73, 75));
        BotonAñadirClientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonAñadirClientes.setText("Añadir / Actualizar Clientes");
        BotonAñadirClientes.setBorder(null);
        BotonAñadirClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirClientesActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAñadirClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 380, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAñadirProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirProveedoresActionPerformed
        // TODO add your handling code here:
        VentanaAñadirProveedores ventana = new VentanaAñadirProveedores();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonAñadirProveedoresActionPerformed

    private void BotonAñadirClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirClientesActionPerformed
        // TODO add your handling code here:
        VentanaAñadirClientes ventana = new VentanaAñadirClientes();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonAñadirClientesActionPerformed

    private void BotonAñadirProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirProductosActionPerformed
        // TODO add your handling code here:
        VentanaAñadirProductos ventana = new VentanaAñadirProductos();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonAñadirProductosActionPerformed

    private void BotonGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenerarFacturaActionPerformed
        // TODO add your handling code here:
        VentanaGenerarFacturas ventana = new  VentanaGenerarFacturas();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonGenerarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Aplicacion_83.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Aplicacion_83.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Aplicacion_83.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Aplicacion_83.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Aplicacion_83().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAñadirClientes;
    private javax.swing.JButton BotonAñadirProductos;
    private javax.swing.JButton BotonAñadirProveedores;
    private javax.swing.JButton BotonGenerarFactura;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
