/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacion;

import entities.Clientes;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Angel
 */
public class VentanaAñadirClientes extends javax.swing.JFrame {
    
        // atributos del JForm
    private EntityManagerFactory emf;
    private controllers.ClientesJpaController controladorClientes;
    
    /**
     * Creates new form VentanaAñadirProveedores2
     */
    public VentanaAñadirClientes() {
        initComponents();
        this.emf = Persistence.createEntityManagerFactory("bdp83");
        // crear el controlador pasandole el manejador de entidades
        this.controladorClientes = new controllers.ClientesJpaController(emf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EntradaApellidoCliente = new javax.swing.JTextField();
        EntradaNombreCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaResultadosClientes = new javax.swing.JTable();
        BotonAñadirTarjeta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EntradaNIFCliente = new javax.swing.JTextField();
        EntradaFechaNacimientoCliente = new javax.swing.JTextField();
        ListaTarjetas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        BotonAñadirCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("NIF:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Apellido:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        EntradaApellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaApellidoClienteActionPerformed(evt);
            }
        });
        jPanel1.add(EntradaApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 130, -1));

        EntradaNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaNombreClienteActionPerformed(evt);
            }
        });
        jPanel1.add(EntradaNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 130, -1));

        TablaResultadosClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaResultadosClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 620, 260));

        BotonAñadirTarjeta.setText("Añadir Tarjeta");
        BotonAñadirTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirTarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAñadirTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Fecha Nacimiento: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Nº Tarjeta: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        EntradaNIFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaNIFClienteActionPerformed(evt);
            }
        });
        jPanel1.add(EntradaNIFCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 130, -1));

        EntradaFechaNacimientoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaFechaNacimientoClienteActionPerformed(evt);
            }
        });
        jPanel1.add(EntradaFechaNacimientoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 130, -1));

        ListaTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaTarjetasActionPerformed(evt);
            }
        });
        jPanel1.add(ListaTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        BotonAñadirCliente.setText("Añadir Cliente");
        BotonAñadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirClienteActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAñadirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel6.setText("Añadir Cliente");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntradaApellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaApellidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaApellidoClienteActionPerformed

    private void EntradaNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaNombreClienteActionPerformed

    private void BotonAñadirTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirTarjetaActionPerformed
        // TODO add your handling code here:
        VentanaAñadirTarjetas ventana = new VentanaAñadirTarjetas();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonAñadirTarjetaActionPerformed

    private void EntradaNIFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaNIFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaNIFClienteActionPerformed

    private void EntradaFechaNacimientoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaFechaNacimientoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaFechaNacimientoClienteActionPerformed

    private void BotonAñadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAñadirClienteActionPerformed

    private void ListaTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaTarjetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaTarjetasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         // bloquear la tabla
        this.TablaResultadosClientes.setEnabled(false);

        // obtener todos los registros de las facturas
        List<Clientes> listaClientes = this.controladorClientes.findClientesEntities();

        // crear las columnas que va a tener nuestra tabla        
        String[] columnas = {"ID", "ID_Tarjeta", "NIF", "Nombre", "Apellido" , "Fecha Nacimiento"};

        // crear un modelo para la tabla
        DefaultTableModel modelo = new DefaultTableModel();

        // poner los identificadores de los campos en el modelo
        modelo.setColumnIdentifiers(columnas);

        // recorrer la lista
        for (Clientes c : listaClientes) {
            // añadir los datos de cada factura a un array de object
            Object[] datosFilaFactura = {c.getIdCliente(), c.getIdtarjetaBancaria(), c.getNifCliente(), c.getNombrecliente(), c.getApellidosCliente(), c.getFechaNacimientocliente()};
            // añadir el array de object como una fila del modelo de la tabla
            modelo.addRow(datosFilaFactura);
        }

        // establecer el modelo a la tabla
        this.TablaResultadosClientes.setModel(modelo);
    }//GEN-LAST:event_formWindowOpened

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
        Main_Aplicacion_83 ventana = new Main_Aplicacion_83();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAñadirClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAñadirCliente;
    private javax.swing.JButton BotonAñadirTarjeta;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JTextField EntradaApellidoCliente;
    private javax.swing.JTextField EntradaFechaNacimientoCliente;
    private javax.swing.JTextField EntradaNIFCliente;
    private javax.swing.JTextField EntradaNombreCliente;
    private javax.swing.JComboBox<String> ListaTarjetas;
    private javax.swing.JTable TablaResultadosClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
